#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# Querying Nginx at its root (/) with a GET request (requesting a page)
#   curl 3.90.65.16 --> returns string "Hello World!"

sudo apt-get -y update
sudo apt-get -y install nginx
echo "listen 80 default_server;" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
