#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Install HAProxy
sudo apt-get update
sudo apt-get -y install haproxy

# Configure HAProxy
sudo bash -c "cat > /etc/haproxy/haproxy.cfg << EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web-01 220921-web-01:80 check
    server web-02 220921-web-02:80 check
EOF"

# Enable HAProxy service
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy service
sudo service haproxy restart
