#!/usr/bin/env bash
# Configure server to be listening on port 80 of all the server's active IPv4 IPs

sudo sed -i 's/listen 8080 default_server;/listen 80 default_server;/' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:8080 default_server ipv6only=on;/listen [::]:80 default_server ipv6only=on;/' /etc/nginx/sites-enabled/default
sudo service nginx restart
