#!/usr/bin/env bash
# Configure server to be listening on port 80 of all the server's active IPv4 IPs

#Install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Set Nginx to listen at port 80 instead of 8080
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo sed -i 's/listen 8080 default_server;/listen 80 default_server;/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:8080 default_server ipv6only=on;/listen [::]:80 default_server ipv6only=on;/g' /etc/nginx/sites-enabled/default

# Restart nginx to effect changes
sudo service nginx restart
