#!/usr/bin/env bash
# Configure server to be listening on port 80 of all the server's active IPv4 IPs
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart
sudo pkill -o nginx
