#!/usr/bin/env bash
#The script iterates 10 times and prints "bad luck" at the 4th time and,
#+prints "good luck" at the 8th time and prints "Best School" for the remaining times
i=1
while ((i <= 10))
do
	if ((i == 4))
	then
		echo "bad luck"
	elif ((i == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++));
done
