#!/usr/bin/env bash
# Prints Hour:0 then No 1-59, then Hour:1 then No 1-59, until Hour is 12
i=0
while ((i <= 12))
do
	echo "Hour: $i"
	j=1
	while ((j < 60))
	do
		echo "$j"
		((j++))
	done
	((i++))
done
