#!/usr/bin/env bash
# You will need to get Apache to run on the container and to
# return a page containing Hello Holberton when querying the root of it.

echo "Hello Holberton" > /var/www/html/index.html

# Start Apache in the foreground
apache2ctl -D FOREGROUND

docker build -t holbertonschool/265-0 .
docker run -p 8080:80 -d holbertonschool/265-0
