#!/usr/bin/env bash
# You will need to get Apache to run on the container and to
# return a page containing Hello Holberton when querying the root of it.

echo "Hello Holberton" > /var/www/html/index.html

# Start Apache
apache2ctl start

# Check if Apache is running
if apache2ctl status | grep -q "apache2 is running"; then
    echo "Apache is running"
    docker build -t holbertonschool/265-0 .
    docker run -p 8080:80 -d holbertonschool/265-0
else
    echo "Apache failed to start"
fi
