#!/usr/bin/env bash
# A bash script that configures a container as follows
# 	nginx must be running as nginx user
# 	nginx must be listening on all active IPs on port 8080

# Stop Nginx
service nginx stop

# Update Nginx configuration
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

# Start Nginx
service nginx start
